import { Event } from '@/types'

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Afrojack: Neon Future Tour',
    description: 'Experience the electrifying sounds of Afrojack live in Cape Town. An unforgettable night of electronic dance music featuring state-of-the-art light shows, massive sound systems, and thousands of fans from across Africa.',
    date: '2026-07-18',
    time: '20:00',
    end_time: '02:00',
    venue: 'Cape Town International Convention Centre',
    address: 'Convention Square, 1 Lower Long St',
    city: 'Cape Town',
    category: 'Electronic',
    image_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
    organizer_name: 'EventGroup SA',
    status: 'published',
    featured: true,
    ticket_types: [
      { id: 't1', event_id: '1', name: 'General Admission', price: 350, quantity: 2000, quantity_sold: 1450 },
      { id: 't2', event_id: '1', name: 'VIP Floor', price: 750, quantity: 500, quantity_sold: 320 },
      { id: 't3', event_id: '1', name: 'Backstage Pass', price: 2500, quantity: 50, quantity_sold: 35 },
    ]
  },
  {
    id: '2',
    title: 'Standard Bank Joy of Jazz Festival',
    description: 'South Africa\'s premier jazz festival returns with world-class local and international artists. Three days of soul-stirring music, great food, and cultural celebration in the heart of Johannesburg.',
    date: '2026-07-25',
    time: '14:00',
    end_time: '23:00',
    venue: 'Sandton Convention Centre',
    address: 'Maude Street, Sandton',
    city: 'Johannesburg',
    category: 'Jazz',
    image_url: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80',
    organizer_name: 'Jazz Entertainment SA',
    status: 'published',
    featured: true,
    ticket_types: [
      { id: 't4', event_id: '2', name: 'Day Pass', price: 450, quantity: 3000, quantity_sold: 2100 },
      { id: 't5', event_id: '2', name: 'Weekend Pass', price: 1100, quantity: 1500, quantity_sold: 890 },
      { id: 't6', event_id: '2', name: 'Premium Table (4 persons)', price: 5500, quantity: 100, quantity_sold: 72 },
    ]
  },
  {
    id: '3',
    title: 'Trevor Noah: Back to Abnormal',
    description: 'South Africa\'s most celebrated comedian returns home with his critically acclaimed world tour. An evening of sharp wit, hilarious observations, and the stories that have made him a global phenomenon.',
    date: '2026-08-02',
    time: '19:30',
    end_time: '22:00',
    venue: 'Artscape Theatre',
    address: 'D.F. Malan Street, Foreshore',
    city: 'Cape Town',
    category: 'Comedy',
    image_url: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&q=80',
    organizer_name: 'Showtime Events',
    status: 'published',
    featured: false,
    ticket_types: [
      { id: 't7', event_id: '3', name: 'Standard', price: 295, quantity: 1800, quantity_sold: 1650 },
      { id: 't8', event_id: '3', name: 'Premium', price: 550, quantity: 400, quantity_sold: 380 },
    ]
  },
  {
    id: '4',
    title: 'Ultra South Africa 2026',
    description: 'The world\'s biggest electronic music festival lands in Johannesburg. Featuring multiple stages, world-renowned DJs, and an audio-visual experience unlike anything else. This is ULTRA.',
    date: '2026-08-08',
    time: '12:00',
    end_time: '23:59',
    venue: 'Nasrec Expo Centre',
    address: 'Nasrec Road, Johannesburg South',
    city: 'Johannesburg',
    category: 'Electronic',
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
    organizer_name: 'Ultra Worldwide',
    status: 'published',
    featured: true,
    ticket_types: [
      { id: 't9', event_id: '4', name: 'General Admission', price: 850, quantity: 10000, quantity_sold: 7800 },
      { id: 't10', event_id: '4', name: 'VIP', price: 1800, quantity: 2000, quantity_sold: 1200 },
      { id: 't11', event_id: '4', name: 'Ultra VIP', price: 4500, quantity: 300, quantity_sold: 180 },
    ]
  },
  {
    id: '5',
    title: 'Cape Town Electronic Music Week',
    description: 'A week-long celebration of underground electronic music featuring local artists, international selectors, intimate venues across the Mother City. From house to techno, drum and bass to ambient.',
    date: '2026-08-15',
    time: '22:00',
    end_time: '06:00',
    venue: 'Various Venues',
    address: 'Cape Town City Centre',
    city: 'Cape Town',
    category: 'Electronic',
    image_url: 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800&q=80',
    organizer_name: 'Cape Town Nights',
    status: 'published',
    featured: false,
    ticket_types: [
      { id: 't12', event_id: '5', name: 'Single Night Pass', price: 180, quantity: 500, quantity_sold: 320 },
      { id: 't13', event_id: '5', name: 'Week Pass', price: 650, quantity: 200, quantity_sold: 145 },
    ]
  },
  {
    id: '6',
    title: 'Stellenbosch Wine & Food Festival',
    description: 'Indulge in the finest South African wines and gourmet cuisine at this prestigious annual festival. Set against the stunning backdrop of the Cape Winelands, enjoy masterclasses, tastings, and live entertainment.',
    date: '2026-08-22',
    time: '11:00',
    end_time: '20:00',
    venue: 'Stellenbosch Town Square',
    address: 'Plein Street, Stellenbosch',
    city: 'Stellenbosch',
    category: 'Food & Wine',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    organizer_name: 'Winelands Events',
    status: 'published',
    featured: false,
    ticket_types: [
      { id: 't14', event_id: '6', name: 'General Tasting', price: 320, quantity: 1500, quantity_sold: 900 },
      { id: 't15', event_id: '6', name: 'Premium Experience', price: 750, quantity: 300, quantity_sold: 180 },
    ]
  },
  {
    id: '7',
    title: 'Durban International Film Festival',
    description: 'Africa\'s longest-running film festival showcasing the best in local and international cinema. Screenings, masterclasses, Q&As with filmmakers, and networking events across the city.',
    date: '2026-09-05',
    time: '09:00',
    end_time: '23:00',
    venue: 'Durban ICC',
    address: '45 Bram Fischer Road, Durban',
    city: 'Durban',
    category: 'Film',
    image_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
    organizer_name: 'UKZN Arts & Culture',
    status: 'published',
    featured: false,
    ticket_types: [
      { id: 't16', event_id: '7', name: 'Single Screening', price: 85, quantity: 500, quantity_sold: 280 },
      { id: 't17', event_id: '7', name: 'Festival Pass', price: 595, quantity: 300, quantity_sold: 120 },
    ]
  },
  {
    id: '8',
    title: 'Afropunk Johannesburg 2026',
    description: 'The iconic Afropunk festival makes its return to Johannesburg. A celebration of Black excellence, creativity, music, art, and fashion. Featuring headlining acts, emerging artists, and activations.',
    date: '2026-09-12',
    time: '12:00',
    end_time: '23:00',
    venue: 'Constitution Hill',
    address: '11 Kotze Street, Braamfontein',
    city: 'Johannesburg',
    category: 'Music',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
    organizer_name: 'Afropunk Global',
    status: 'published',
    featured: true,
    ticket_types: [
      { id: 't18', event_id: '8', name: 'General Admission', price: 550, quantity: 5000, quantity_sold: 3200 },
      { id: 't19', event_id: '8', name: 'VIP', price: 1200, quantity: 800, quantity_sold: 420 },
    ]
  },
]

export const CATEGORIES = ['All', 'Electronic', 'Jazz', 'Comedy', 'Music', 'Food & Wine', 'Film', 'Sports', 'Theatre']
export const CITIES = ['All Cities', 'Cape Town', 'Johannesburg', 'Durban', 'Pretoria', 'Stellenbosch']
